name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: ilammy/msvc-dev-cmd@v1
    
    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Build CPU version
      env:
        TABVOICE_NO_CUDA: "1"
        LIBCLANG_PATH: "C:\\Program Files\\LLVM\\bin"
      run: cargo build --release --verbose

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: tabvoice-cpu-only
        path: target/release/tabvoice.exe
